name: Update ROCK

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0,4,8,12,16,20 * * *'

jobs:
  build:
    uses: canonical/observability/.github/workflows/rock-update.yaml@fix/rock-update-versions
    with:
      rock-name: prometheus
      source-repo: prometheus/prometheus
      check-go: true
      update-script: |
        # The caller must provide $application_src and $rockcraft_yaml
        #   $application_src: The root folder of the cloned upstream project
        #   $rockcraft_yaml: Path of the rockcraft.yaml to update
        #
        ## Node dependency
        yq -i 'del(.parts.prometheus.build-snaps.[] | select(. == "node/*"))' "$rockcraft_yaml"
        ver="$(sed -En 's|\s*"@types/node":\s*"\^*([0-9]+)(\.[0-9])+.*",|\1|p' $application_src/web/ui/package.json)" \
          yq -i '.parts.prometheus.build-snaps += "node/"+strenv(ver)+"/stable"' "$rockcraft_yaml"
