name: Update ROCK

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0,4,8,12,16,20 * * *'

jobs:
  build:
    uses: canonical/observability/.github/workflows/rock-update.yaml@main
    with:
      rock-name: prometheus
      source-repo: prometheus/prometheus
      check-go: true
      update-script: |
        # The caller must provide $application_src and $rockcraft_yaml
        #   $application_src: The root folder of the cloned upstream project
        #   $rockcraft_yaml: Path of the rockcraft.yaml to update
        #
        ## Node dependency
        node_version="$(cat $application_src/web/ui/package.json | sed -n 's|\"@types/node\":\s\"\(.*\)\",|\1|p')"
        echo $node_version
        node_version="${node_version##*^}"
        node_version="${node_version%%\.*}"
        echo "Node Version: $node_version"
        yq -i 'del(.parts.prometheus.build-snaps.[] | select(. == "node/*"))' "$rockcraft_yaml"
        ver="$node_version" yq -i '.parts.prometheus.build-snaps += "node/"+strenv(ver)+"/stable"' "$rockcraft_yaml"
