name: Update rock

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    uses: canonical/observability/.github/workflows/rock-update.yaml@v0
    with:
      rock-name: prometheus
      source-repo: prometheus/prometheus
      check-go: true
      update-script: |
        # The caller must provide \$application_src and \$rockcraft_yaml
        #   \$application_src: The root folder of the cloned upstream project
        #   \$rockcraft_yaml: Path of the rockcraft.yaml to update
        #
        ## Node dependency
        node_version=$(sed -E 's/^v?([0-9]+).*/\1/' "$application_src/web/ui/.nvmrc")
        yq -i 'del(.parts.prometheus.build-snaps.[] | select(. == "node/*"))' "\$rockcraft_yaml"
        ver="\$node_version" yq -i '.parts.prometheus.build-snaps += "node/"+strenv(ver)+"/stable"' "\$rockcraft_yaml"
    secrets: inherit
